const replacements: Array<[RegExp, string]> = [
  [/\bOdul\b/g, "Ödül"],
  [/\bodul\b/g, "ödül"],
  [/\bOdulu\b/g, "Ödülü"],
  [/\bodulu\b/g, "ödülü"],
  [/\bOduller\b/g, "Ödüller"],
  [/\boduller\b/g, "ödüller"],
  [/\bUrun\b/g, "Ürün"],
  [/\burun\b/g, "ürün"],
  [/\bUrunler\b/g, "Ürünler"],
  [/\burunler\b/g, "ürünler"],
  [/\bDiger\b/g, "Diğer"],
  [/\bdiger\b/g, "diğer"],
  [/\bAhsap\b/g, "Ahşap"],
  [/\bahsap\b/g, "ahşap"],
  [/\bOlcu\b/g, "Ölçü"],
  [/\bolcu\b/g, "ölçü"],
  [/\bOzel\b/g, "Özel"],
  [/\bozel\b/g, "özel"],
  [/\bHizli\b/g, "Hızlı"],
  [/\bhizli\b/g, "hızlı"],
  [/\bUretim\b/g, "Üretim"],
  [/\buretim\b/g, "üretim"],
  [/\bIletisim\b/g, "İletişim"],
  [/\biletisim\b/g, "iletişim"],
  [/\bIncele\b/g, "İncele"],
  [/\bKatalogu\b/g, "Kataloğu"],
  [/\bkatalogu\b/g, "kataloğu"],
  [/\bKisiye\b/g, "Kişiye"],
  [/\bkisiye\b/g, "kişiye"],
  [/\bIsimlik\b/g, "İsimlik"],
  [/\bisimlik\b/g, "isimlik"],
  [/\bAluminyum\b/g, "Alüminyum"],
  [/\baluminyum\b/g, "alüminyum"],
  [/\bAnahtarlik\b/g, "Anahtarlık"],
  [/\banahtarlik\b/g, "anahtarlık"],
  [/\bBaskili\b/g, "Baskılı"],
  [/\bbaskili\b/g, "baskılı"],
  [/\bYonlendirme\b/g, "Yönlendirme"],
  [/\byonlendirme\b/g, "yönlendirme"],
  [/\bLevhasi\b/g, "Levhası"],
  [/\blevhasi\b/g, "levhası"],
  [/\bMuzik\b/g, "Müzik"],
  [/\bmuzik\b/g, "müzik"],
  [/\bAksesuarlari\b/g, "Aksesuarları"],
  [/\baksesuarlari\b/g, "aksesuarları"],
  [/\bAnisi\b/g, "Anısı"],
  [/\banisi\b/g, "anısı"],
  [/\bBos\b/g, "Boş"],
  [/\bbos\b/g, "boş"],
  [/\bCesitleri\b/g, "Çeşitleri"],
  [/\bcesitleri\b/g, "çeşitleri"],
  [/\bFarkli\b/g, "Farklı"],
  [/\bfarkli\b/g, "farklı"],
  [/\bAltin\b/g, "Altın"],
  [/\baltin\b/g, "altın"],
  [/\bGumus\b/g, "Gümüş"],
  [/\bgumus\b/g, "gümüş"],
  [/\bSeffaf\b/g, "Şeffaf"],
  [/\bseffaf\b/g, "şeffaf"],
  [/\bBaski\b/g, "Baskı"],
  [/\bbaski\b/g, "baskı"],
  [/\bTasarim\b/g, "Tasarım"],
  [/\btasarim\b/g, "tasarım"],
  [/\bKazima\b/g, "Kazıma"],
  [/\bkazima\b/g, "kazıma"],
  [/\bIcin\b/g, "İçin"],
  [/\bicin\b/g, "için"],
  [/\bHakkinda\b/g, "Hakkında"],
  [/\bhakkinda\b/g, "hakkında"],
  [/\bGonder\b/g, "Gönder"],
  [/\bgonder\b/g, "gönder"],
  [/\bGore\b/g, "Göre"],
  [/\bgore\b/g, "göre"],
  [/\bUzerinden\b/g, "Üzerinden"],
  [/\buzerinden\b/g, "üzerinden"],
  [/\bTurkiye\b/g, "Türkiye"],
];

export function tr(input: string | null | undefined) {
  if (!input) {
    return "";
  }

  return replacements.reduce((text, [pattern, value]) => text.replace(pattern, value), input);
}
